apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azure_secrets.azurename }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azure_secrets.azureStorageAccountName }}
  azurestorageaccountkey: {{ .Values.azure_secrets.storageKey }}