apiVersion: v1
kind: Secret
metadata:
  name: ovaledgedockersecret
  namespace: {{ .Values.namespace }}
  resourceVersion: "23421"
  uid: 7ce6487b-9209-4ae8-ace1-b5c95155495b
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJvdmFsZWRnZWxsYyIsInBhc3N3b3JkIjoiNTg1NTYyZTQtMTcyYy00MjkxLTg5OGEtMmVhYmFmNDgyOTY5IiwiZW1haWwiOiJwcmF0YXByZWRkeS50YXBwZXRhQG92YWxlZGdlLmNvbSIsImF1dGgiOiJiM1poYkdWa1oyVnNiR002TlRnMU5UWXlaVFF0TVRjeVl5MDBNamt4TFRnNU9HRXRNbVZoWW1GbU5EZ3lPVFk1In19fQ=="
type: kubernetes.io/dockerconfigjson