apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  namespace: {{ .Values.namespace }}
  labels:
    app: nifi
spec:
  type: LoadBalancer
  ports:
    - port: 9443
      targetPort: https
      protocol: TCP
      name: https
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector: 
    app: nifi
