apiVersion: v1
kind: Service
metadata:
  name: oe-service
  namespace: {{ .Values.namespace }}
  labels:
    app: ovaledge-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ovaledge-ui